[package]
edition = "2021"
name = "uiua"
readme = "readme.md"
repository = "https://github.com/kaikalii/uiua"
version = "0.1.0"

[dependencies]
ariadne = "0.2.0"
clap.features = ["derive"]
clap.optional = true
clap.version = "4"
ctrlc.optional = true
ctrlc.version = "3"
image = "0.24.5"
instant = "0.1.12"
nanbox = "0.2.0"
notify.optional = true
notify.version = "5"
open.optional = true
open.version = "4"
rand.default-features = false
rand.features = ["small_rng"]
rand.version = "0.8.5"
term_size.optional = true
term_size.version = "0.3.2"

[features]
binary = ["ctrlc", "notify", "term_size", "clap", "open"]
debug = []
default = ["binary"]

[[bin]]
name = "uiua"

[workspace]
members = ["site"]
