[package]
edition = "2021"
name = "uiua"
readme = "readme.md"
repository = "https://github.com/uiua-lang/uiua"
version = "0.1.0"

[dependencies]
ariadne = "0.2.0"
bufreaderwriter = "0.2.4"
clap.features = ["derive"]
clap.optional = true
clap.version = "4"
color-backtrace.optional = true
color-backtrace.version = "0.5.1"
crossbeam-channel.optional = true
crossbeam-channel.version = "0.5.8"
ctrlc.optional = true
ctrlc.version = "3"
ecow.git = "https://github.com/typst/ecow"
enum-iterator = "1"
hound = "3"
image.default-features = false
image.features = [
  "bmp",
  "gif",
  "ico",
  "jpeg",
  "png",
]
image.version = "0.24.5"
indexmap.features = ["serde"]
indexmap.optional = true
indexmap.version = "1"
instant = "0.1.12"
notify.optional = true
notify.version = "5"
open.optional = true
open.version = "4"
rand.default-features = false
rand.features = ["small_rng"]
rand.version = "0.8.5"
regex = "1.9"
rodio.optional = true
rodio.version = "0.17.1"
serde.features = ["derive"]
serde.optional = true
serde.version = "1"
serde_yaml.optional = true
serde_yaml.version = "0.9.25"
term_size = "0.3.2"
tokio.features = ["io-std", "rt"]
tokio.optional = true
tokio.version = "1"
tower-lsp.optional = true
tower-lsp.version = "0.19.0"
viuer.optional = true
viuer.version = "0.6.2"

[features]
audio = ["rodio"]
binary = ["ctrlc", "notify", "clap", "open", "color-backtrace", "lsp"]
debug = []
default = ["binary", "audio", "terminal_image"]
lsp = ["tower-lsp", "tokio"]
profile = ["crossbeam-channel", "serde", "serde_yaml", "indexmap"]
terminal_image = ["viuer"]

[[bin]]
name = "uiua"

[workspace]
members = ["site"]
