[package]
edition = "2021"
name = "uiua"
readme = "readme.md"
repository = "https://github.com/kaikalii/uiua"
version = "0.1.0"

[dependencies]
ariadne = "0.2.0"
color-backtrace = "0.5.1"
instant = "0.1.12"
nanbox = "0.2.0"
term_size = "0.3.2"
viuer = "0.6.2"

[dependencies.clap]
features = ["derive"]
optional = true
version = "4"

[dependencies.ctrlc]
optional = true
version = "3"

[dependencies.image]
default-features = false
features = [
  "bmp",
  "gif",
  "ico",
  "jpeg",
  "png",
]
version = "0.24.5"

[dependencies.notify]
optional = true
version = "5"

[dependencies.open]
optional = true
version = "4"

[dependencies.rand]
default-features = false
features = ["small_rng"]
version = "0.8.5"

[features]
binary = ["ctrlc", "notify", "clap", "open"]
debug = []
default = ["binary"]

[[bin]]
name = "uiua"

[workspace]
members = ["site"]
