[package]
edition = '2021'
name = 'uiua'
version = '0.1.0'

[dependencies]
ascend = '0.3.0'
enum-iterator = '1.3'
im = '15'
nohash-hasher = '0.2.0'

puffin.optional = true
puffin.version = '0.14.3'
puffin_http.optional = true
puffin_http.version = '0.11.1'

[features]
profile = ['puffin', 'puffin_http']
