[package]
edition = "2021"
name = "uiua"
readme = "readme.md"
repository = "https://github.com/kaikalii/uiua"
version = "0.1.0"

[dependencies]
clap.features = ["derive"]
clap.version = "4"
ctrlc = "3"
nanbox = "0.2.0"
notify = "5"
term_size = "0.3.2"

puffin.optional = true
puffin.version = "0.14.3"
puffin_http.optional = true
puffin_http.version = "0.11.1"

[features]
debug = []
profile = ["puffin", "puffin_http"]
