[package]
edition = "2021"
name = "site"
version = "0.1.0"

[dependencies]
base64 = "0.21.0"
console_error_panic_hook = "0.1.7"
enum-iterator = "1"
image = "0.24.5"
instant.features = ['wasm-bindgen']
instant.version = "0.1.12"
js-sys = "0.3"
leptos = "0.4.5"
leptos_router.features = ["csr"]
leptos_router.version = "0.4.5"
regex = "1.9"
uiua.default-features = false
uiua.path = ".."
urlencoding = "2"
wasm-bindgen = "0.2.84"
web-sys.features = [
  "CssStyleDeclaration",
  "Storage",
  "HtmlAudioElement",
  "Selection",
  "Node",
  "Clipboard",
  "ClipboardEvent",
  "DataTransfer",
  "Navigator",
  "Permissions",
  "ScrollIntoViewOptions",
  "ScrollBehavior",
  "ScrollLogicalPosition",
]
web-sys.version = "0.3.61"
