[package]
edition = "2021"
name = "site"
version = "0.1.0"

[dependencies]
base64 = "0.21.0"
console_error_panic_hook = "0.1.7"
enum-iterator = "1"
image = "0.24.5"
wasm-bindgen = "0.2.84"

[dependencies.web-sys]
features = ["CssStyleDeclaration", "Storage", "HtmlAudioElement"]
version = "0.3.61"

[dependencies.instant]
features = ['wasm-bindgen']
version = "0.1.12"

[dependencies.leptos]
version = "0.4.5"

[dependencies.leptos_router]
features = ["csr"]
version = "0.4.5"

[dependencies.rand]
default-features = false
features = ["small_rng"]
version = "0.8.5"

[dependencies.uiua]
default-features = false
path = ".."
