[package]
edition = "2021"
name = "site"
version = "0.1.0"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.84"

[dependencies.web-sys]
features = ["CssStyleDeclaration"]
version = "0.3.61"

[dependencies.instant]
features = ['wasm-bindgen']
version = "0.1.12"

[dependencies.leptos]
features = ["stable"]
version = "0.2.4"

[dependencies.leptos_router]
features = ["stable", "csr"]
version = "0.2.4"

[dependencies.rand]
default-features = false
features = ["small_rng"]
version = "0.8.5"

[dependencies.uiua]
default-features = false
path = ".."
